spring:
  application:
    name: customer
  profiles:
    active: production

# ACTUATOR INFO
info:
  app:
    name: "Customer"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}

#REFRESH
management:
  endpoints:
    web:
      exposure:
        include: '*'